### ISSUE TITLE
Incorrectlly assigned timestamps for global forecast on multiple dates

### ISSUE THREAD

**Issue by sbAsma** [clessig/atmorep#25]
When dates with different months are set in `evaluate.py`, for example:
```
  mode, options = 'global_forecast', { 'fields[0][2]' : [96],
                                      'dates' : [[2021, 2, 10, 12], [2021, 3, 10, 12], [2021, 4, 10, 12]],
                                      'token_overlap' : [0, 0],
                                      'forecast_num_tokens' : 1,
                                      'attention' : False }

  Evaluator.evaluate( mode, model_id, options)
```
The variable `self.years_months` in `multifield_data_sampler.py` (line 353) doesn't receive all months. And when a print statement is performed, the output is:
```
self.years_months = [(2021, 2)]
``` 
However, it is not affecting the run.

**Comment by grassesi** [comment]
I had a similar issue a while ago and fixed it for my masterthesis, do you remember on what commmit/branch you were working on ?

**Comment by iluise** [comment]
Hi, I think this has been fixed in the new version. Could you please retry with the `develop` branch and write here the outcome?

**Comment by grassesi** [comment]
I think the error still persists at least on commit `1fbb02a008688bd7068dd0762f5e272deada3e0d` (current develop). Both prediction and target result data only contains the timestamps `2021-02-10T10`-`2021-02-10T12`. Source contains hourly timestamps from `2021-02-09T01`-`2021-02-10T12`.

**Comment by iluise** [comment]
Hi, yes we should have isolated the problem and added a temporal fix here: https://github.com/clessig/atmorep/issues/33
Can you try it out and let me know if it fixes it? if yes, I suggest to close this issue and continue in the other one which is more specific.

**Comment by grassesi** [comment]
I tried your fix, but for multiple dates I will only ever get predictions for the first date

**Comment by iluise** [comment]
Uhm, interesting. Can you give me the `model_id` you are using so I can take a look?

**Comment by grassesi** [comment]
I am using the the `id3qou60es` temperature model. Also I further investigated the faulty behavior and it seems like prediction samples for the other dates will be also generated, but will be assigned the timestamps from the first date

**Comment by iluise** [comment]
Hi, I tried again with `iluise/head` (which contains the fix) and the pretrained run temperature as you indicated. I used the following dates:

`````
'dates' : [ 
              [2021, 1, 10, 12] , [2021, 1, 11, 0], [2021, 1, 11, 12], [2021, 1, 12, 0]
]
``````

This is what I get: 

`````````
>>> import numpy as np
>>> import zarr
>>> store = zarr.ZipStore("results/idxf8j65xh/results_idxf8j65xh_epoch00000_pred.zarr")
>>> root = zarr.group(store)
>>> all_dates = []
>>> for i in root["temperature"]:
...     all_dates.append(root[f"temperature/{i}"].datetime[:])
... 
>>> np.unique(np.array(all_dates))
array(['2021-01-10T07:00:00.000000000', '2021-01-10T08:00:00.000000000',
       '2021-01-10T09:00:00.000000000', '2021-01-10T10:00:00.000000000',
       '2021-01-10T11:00:00.000000000', '2021-01-10T12:00:00.000000000',
       '2021-01-10T19:00:00.000000000', '2021-01-10T20:00:00.000000000',
       '2021-01-10T21:00:00.000000000', '2021-01-10T22:00:00.000000000',
       '2021-01-10T23:00:00.000000000', '2021-01-11T00:00:00.000000000',
       '2021-01-11T07:00:00.000000000', '2021-01-11T08:00:00.000000000',
       '2021-01-11T09:00:00.000000000', '2021-01-11T10:00:00.000000000',
       '2021-01-11T11:00:00.000000000', '2021-01-11T12:00:00.000000000',
       '2021-01-11T19:00:00.000000000', '2021-01-11T20:00:00.000000000',
       '2021-01-11T21:00:00.000000000', '2021-01-11T22:00:00.000000000',
       '2021-01-11T23:00:00.000000000', '2021-01-12T00:00:00.000000000'],
      dtype='datetime64[ns]')
>>> exit()
`````````

Which is 6x4 = 24 so what we expect no? 

Could you please try with `iluise/head` and see if the problem persists?

**Comment by grassesi** [comment]
looks good now, I also implemented a regression test on #15 to check the present timestamps against the expected timestamps inferred from the model_id<...>.json

**Comment by iluise** [comment]
super, thanks!
